# Generated by Django 4.0.4 on 2022-05-24 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_article_pub_date_article_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title']},
        ),
    ]
