# Generated by Django 4.0.4 on 2022-05-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_article_editor_alter_article_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post',
            field=models.CharField(max_length=200),
        ),
    ]
