# Generated by Django 4.0.4 on 2022-05-31 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_newsletterrecipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.DeleteModel(
            name='NewsLetterRecipient',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
        migrations.DeleteModel(
            name='tags',
        ),
    ]
